# Generated by Django 4.0.4 on 2022-04-29 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0002_table_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name='Imagem do produto'),
            preserve_default=False,
        ),
    ]
